[tasks."version:up"]
script = '''
version-make up -rz package.json
'''

[tasks."version:tag"]
script = '''
git tag v$(version-make show package.json)
'''

[tasks."version:untag"]
script = '''
git tag v$(version-make show package.json) -d
'''
